
// Follow the Supabase Edge Function signature
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface ScheduleEvent {
  title: string;
  day: number;
  hour: number;
  duration: number;
  type: string;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Get the request body
    const { schedule } = await req.json();

    // Handle if no schedule is provided
    if (!schedule || !Array.isArray(schedule)) {
      return new Response(
        JSON.stringify({ error: 'No valid schedule provided' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Get authorization header from request
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: 'No authorization header provided' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Extract the JWT token and the user's access token
    const jwtToken = authHeader.replace('Bearer ', '');

    // In a real implementation, we would verify the JWT and extract user info
    // For now, we'll simulate the process of getting the Google access token
    console.log("Processing schedule with token:", jwtToken.substring(0, 10) + "...");

    // Get events from the schedule and format for Google Calendar
    const googleEvents = schedule.map((event: ScheduleEvent) => {
      // Calculate the date for this event
      const today = new Date();
      const startDate = new Date(today);
      
      // Adjust to the start of the week (Sunday)
      const dayDiff = today.getDay(); // 0 for Sunday, 1 for Monday, etc.
      startDate.setDate(today.getDate() - dayDiff);
      
      // Add the event's day (0 for Sunday, 1 for Monday, etc.)
      const eventDate = new Date(startDate);
      eventDate.setDate(startDate.getDate() + event.day);
      
      // Set the hour
      const hourWhole = Math.floor(event.hour);
      const hourFraction = event.hour - hourWhole;
      const minutes = Math.round(hourFraction * 60);
      
      eventDate.setHours(hourWhole, minutes, 0, 0);
      
      // Calculate end time
      const endDate = new Date(eventDate);
      const durationHours = Math.floor(event.duration);
      const durationMinutes = Math.round((event.duration - durationHours) * 60);
      endDate.setHours(
        endDate.getHours() + durationHours,
        endDate.getMinutes() + durationMinutes,
        0, 0
      );
      
      // Format dates for Google Calendar API
      const startDateTime = eventDate.toISOString();
      const endDateTime = endDate.toISOString();
      
      return {
        summary: event.title,
        description: `Event type: ${event.type}\nGenerated by ScheduleWise`,
        start: {
          dateTime: startDateTime,
          timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
        },
        end: {
          dateTime: endDateTime,
          timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
        },
        colorId: getGoogleColorIdForEventType(event.type)
      };
    });

    // In a full implementation, we would make actual API calls to Google Calendar
    // For now, we'll log what would be added and simulate success
    console.log(`Would add ${googleEvents.length} events to Google Calendar`);
    googleEvents.forEach(event => {
      console.log(`- ${event.summary} (${event.start.dateTime} to ${event.end.dateTime})`);
    });

    // Simulate successful response
    return new Response(
      JSON.stringify({ 
        success: true, 
        eventsAdded: googleEvents.length,
        message: 'Schedule successfully synced with Google Calendar'
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error("Error in sync-google-calendar function:", error);
    
    return new Response(
      JSON.stringify({ error: error.message || 'Internal server error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});

// Helper function to map event types to Google Calendar color IDs
function getGoogleColorIdForEventType(type: string): string {
  // Google Calendar color IDs (1-11)
  // See: https://developers.google.com/calendar/api/v3/reference/colors/get
  const colorMap: Record<string, string> = {
    'meeting': '1',     // Lavender
    'deep-work': '2',   // Sage
    'workout': '3',     // Grape
    'meals': '4',       // Flamingo
    'learning': '5',    // Banana
    'relaxation': '6',  // Tangerine
    'work': '7',        // Peacock
    'commute': '8',     // Graphite
    'sleep': '9',       // Blueberry
  };
  
  return colorMap[type] || '10'; // Default to Basil (10) if type not found
}
