
// Follow the Supabase Edge Function signature
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface ScheduleEvent {
  title: string;
  day: number;
  hour: number;
  duration: number;
  type: string;
  description?: string;
}

serve(async (req) => {
  console.log("Received request to sync-google-calendar function");
  
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    console.log("Handling CORS preflight request");
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Get the request body
    const requestData = await req.json();
    const { schedule } = requestData;
    
    console.log(`Received schedule with ${schedule?.length || 0} events`);

    // Handle if no schedule is provided
    if (!schedule || !Array.isArray(schedule)) {
      console.error("No valid schedule provided in request");
      return new Response(
        JSON.stringify({ error: 'No valid schedule provided' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Get authorization header from request
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      console.error("No authorization header provided");
      return new Response(
        JSON.stringify({ error: 'No authorization header provided' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Extract the JWT token
    const jwtToken = authHeader.replace('Bearer ', '');
    console.log("JWT token extracted from request");
    
    // Verify the JWT token and get the user's access token
    // This assumes you're using Supabase Auth and the token contains the user's Google access token
    const supabaseUrl = Deno.env.get('SUPABASE_URL') || '';
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || '';
    
    if (!supabaseUrl || !supabaseKey) {
      console.error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY environment variables");
      throw new Error('Server configuration error - missing required environment variables');
    }
    
    console.log("Getting user info from Supabase");
    
    // Get user info from Supabase
    const userResponse = await fetch(`${supabaseUrl}/auth/v1/user`, {
      headers: {
        'Authorization': `Bearer ${jwtToken}`,
        'apikey': supabaseKey
      }
    });
    
    if (!userResponse.ok) {
      const errorText = await userResponse.text();
      console.error(`Failed to verify user token. Status: ${userResponse.status}, Response: ${errorText}`);
      throw new Error('Failed to verify user token');
    }
    
    const userData = await userResponse.json();
    console.log("User data retrieved from Supabase");
    
    // Get the user's Google access token
    // This assumes the token is stored in the user's provider_token field
    const googleAccessToken = userData.app_metadata?.provider_token || userData.provider_token;
    
    if (!googleAccessToken) {
      console.error("No Google access token found in user data", userData);
      throw new Error('No Google access token found. Please reconnect your Google account.');
    }
    
    console.log("Google access token found, preparing to create calendar events");

    // Get events from the schedule and format for Google Calendar
    const googleEvents = schedule.map((event: ScheduleEvent) => {
      // Calculate the date for this event
      const today = new Date();
      const startDate = new Date(today);
      
      // Adjust to the start of the week (Sunday)
      const dayDiff = today.getDay(); // 0 for Sunday, 1 for Monday, etc.
      startDate.setDate(today.getDate() - dayDiff);
      
      // Add the event's day (0 for Sunday, 1 for Monday, etc.)
      const eventDate = new Date(startDate);
      eventDate.setDate(startDate.getDate() + event.day);
      
      // Set the hour
      const hourWhole = Math.floor(event.hour);
      const hourFraction = event.hour - hourWhole;
      const minutes = Math.round(hourFraction * 60);
      
      eventDate.setHours(hourWhole, minutes, 0, 0);
      
      // Calculate end time
      const endDate = new Date(eventDate);
      const durationHours = Math.floor(event.duration);
      const durationMinutes = Math.round((event.duration - durationHours) * 60);
      endDate.setHours(
        endDate.getHours() + durationHours,
        endDate.getMinutes() + durationMinutes,
        0, 0
      );
      
      // Format dates for Google Calendar API
      const startDateTime = eventDate.toISOString();
      const endDateTime = endDate.toISOString();
      
      return {
        summary: event.title,
        description: event.description || `Event type: ${event.type}\nGenerated by ScheduleWise`,
        start: {
          dateTime: startDateTime,
          timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
        },
        end: {
          dateTime: endDateTime,
          timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
        },
        colorId: getGoogleColorIdForEventType(event.type)
      };
    });
    
    console.log(`Formatted ${googleEvents.length} events for Google Calendar`);

    // Make actual API calls to Google Calendar
    const successfulEvents = [];
    const failedEvents = [];
    
    // Create a calendar for our app if it doesn't exist
    const calendarName = "ScheduleWise";
    let calendarId = "primary"; // Default to primary calendar
    
    try {
      console.log("Checking for existing ScheduleWise calendar");
      // First check if our calendar already exists
      const calendarListResponse = await fetch('https://www.googleapis.com/calendar/v3/users/me/calendarList', {
        headers: {
          'Authorization': `Bearer ${googleAccessToken}`,
          'Content-Type': 'application/json'
        }
      });
      
      if (!calendarListResponse.ok) {
        const errorText = await calendarListResponse.text();
        console.error(`Failed to get calendar list. Status: ${calendarListResponse.status}, Response: ${errorText}`);
        throw new Error(`Failed to get calendar list: ${calendarListResponse.status}`);
      }
      
      const calendarList = await calendarListResponse.json();
      console.log(`Found ${calendarList.items?.length || 0} calendars`);
      
      const existingCalendar = calendarList.items.find((cal: any) => cal.summary === calendarName);
      
      if (existingCalendar) {
        console.log(`Found existing ScheduleWise calendar with ID: ${existingCalendar.id}`);
        calendarId = existingCalendar.id;
      } else {
        console.log("No ScheduleWise calendar found, creating a new one");
        // Create a new calendar for our app
        const createCalendarResponse = await fetch('https://www.googleapis.com/calendar/v3/calendars', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${googleAccessToken}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            summary: calendarName,
            description: "Calendar created by ScheduleWise for your AI-generated schedule"
          })
        });
        
        if (!createCalendarResponse.ok) {
          const errorText = await createCalendarResponse.text();
          console.error(`Failed to create calendar. Status: ${createCalendarResponse.status}, Response: ${errorText}`);
          throw new Error(`Failed to create calendar: ${createCalendarResponse.status}`);
        }
        
        const newCalendar = await createCalendarResponse.json();
        console.log(`Created new ScheduleWise calendar with ID: ${newCalendar.id}`);
        calendarId = newCalendar.id;
      }
    } catch (calendarError) {
      console.error("Error creating/finding calendar:", calendarError);
      // Continue with primary calendar if there's an error
      console.log("Falling back to primary calendar");
    }
    
    console.log(`Using calendar ID: ${calendarId} to add events`);
    
    // Add each event to the calendar
    for (const event of googleEvents) {
      try {
        console.log(`Adding event "${event.summary}" to calendar`);
        
        const response = await fetch(`https://www.googleapis.com/calendar/v3/calendars/${calendarId}/events`, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${googleAccessToken}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify(event)
        });
        
        if (response.ok) {
          const addedEvent = await response.json();
          console.log(`Successfully added event with ID: ${addedEvent.id}`);
          successfulEvents.push(addedEvent);
        } else {
          const errorData = await response.json();
          console.error(`Error adding event: ${event.summary}`, errorData);
          failedEvents.push({ event, error: errorData });
        }
      } catch (eventError) {
        console.error(`Error adding event: ${event.summary}`, eventError);
        failedEvents.push({ event, error: eventError.message });
      }
    }
    
    console.log(`Added ${successfulEvents.length} events successfully, ${failedEvents.length} failed`);

    return new Response(
      JSON.stringify({ 
        success: successfulEvents.length > 0, 
        eventsAdded: successfulEvents.length,
        eventsFailed: failedEvents.length,
        message: `Added ${successfulEvents.length} events to Google Calendar${failedEvents.length > 0 ? ` (${failedEvents.length} failed)` : ''}`,
        calendarId: calendarId
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error("Error in sync-google-calendar function:", error);
    
    return new Response(
      JSON.stringify({ error: error.message || 'Internal server error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});

// Helper function to map event types to Google Calendar color IDs
function getGoogleColorIdForEventType(type: string): string {
  // Google Calendar color IDs (1-11)
  // See: https://developers.google.com/calendar/api/v3/reference/colors/get
  const colorMap: Record<string, string> = {
    'meeting': '1',     // Lavender
    'deep-work': '2',   // Sage
    'workout': '3',     // Grape
    'meals': '4',       // Flamingo
    'learning': '5',    // Banana
    'relaxation': '6',  // Tangerine
    'work': '7',        // Peacock
    'commute': '8',     // Graphite
    'sleep': '9',       // Blueberry
  };
  
  return colorMap[type] || '10'; // Default to Basil (10) if type not found
}
